### ISSUE TITLE
deprecate in favour of babel-plugin-dotenv-import

### ISSUE THREAD

**Issue by goatandsheep** [VojtechBartos/react-native-dot-env#2]
the new react native dotenv is [here](https://github.com/tusbar/babel-plugin-dotenv-import)

**Comment by VojtechBartos** [comment]
looks like that package handles and wraps the env vars in bundle, this one leverages the .plist file which is safer if you deliver bundle remotely or do i miss something?

**Comment by goatandsheep** [comment]
I'll be honest, I don't know what a plist is! I have been going around trying to catch packages that fed off a package that is being deprecated https://github.com/zetachang/react-native-dotenv/ . Due to lack of maintenance, a lot of forks were created and published. After looking again, yours is not that! My apologies.
